version: '3'
services:
  mod-site:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mod-site
    volumes:
      - ./logs:/app/logs:rw
      - ./data:/app/data:rw
    ports:
    - "5999:5002"
    networks:
      - default
      - nginx-net
    restart: unless-stopped
    command: /app/run_server.sh
    environment:
      VIRTUAL_HOST: modifinder.gnps2.org
      VIRTUAL_PORT: 5002
      LETSENCRYPT_HOST: modifinder.gnps2.org
      LETSENCRYPT_EMAIL: mwang87@gmail.com


networks:
  nginx-net:
    external:
      name: nginx-net
