version: '3'
services:
  modifinder-dash:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: modifinder-dash
    volumes:
      - ./logs:/app/logs:rw
      - ./SIRIUS:/app/SIRIUS:rw
    ports:
    - "5999:5000"
    networks:
      - default
      - nginx-net
    restart: unless-stopped
    command: /app/run_server.sh
    environment:
      VIRTUAL_HOST: modifinder.gnps2.org
      VIRTUAL_PORT: 5000
      LETSENCRYPT_HOST: modifinder.gnps2.org
      LETSENCRYPT_EMAIL: mwang87@gmail.com


networks:
  nginx-net:
    external:
      name: nginx-net
